
- name: Create Hadoop User on all nodes
  hosts: all
  remote_user: ansible_user
  gather_facts: true
  become: yes
  roles:
    - create-Hadoop-user

- name: Distribute Authentication Key-pairs 
  hosts: masters
  remote_user: ansible_user
  gather_facts: true
  become: yes 
  roles:
    - Distribute-Authentication-KeyPairs    

- name: Copy key file into the authorized key store
  hosts: workers
  remote_user: ansible_user
  gather_facts: true
  become: yes 
  tasks:
    - name: Copy key file into the authorized key store
      shell: "cat /home/{{ user }}/.ssh/master.pub >> /home/{{ user }}/.ssh/authorized_keys"
     

- name: Install Java 
  remote_user: ansible_user
  gather_facts: no
  become: yes
  hosts: all
  roles:
    - install-java

- name: Install Hadoop
  hosts: all
  remote_user: ansible_user
  gather_facts: no
  become: yes
  roles:
    - install-Hadoop


# - name: Format HDFS Namenode
#   hosts: masters
#   remote_user: ansible_user
#   gather_facts: no
#   become: yes
#   tasks:
#     - name: Format HDFS Namenode
#       shell: hdfs namenode -format -force

     
      







      
  

