---
# tasks file for Distribute-Authentication-KeyPairs
- name: Get Lastest Public From Hadoop Master
  fetch: 
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /tmp/id_{{ ansible_host }}_{{ user }}.pub
    flat: yes

- name: Add Cluster Public Key for Hadoop
  authorized_key: 
    user={{ user }} 
    key="{{ lookup('file', '/tmp/id_{{master_ip}}_{{user}}.pub') }}"

- name: Add User Public Key for Hadoop
  authorized_key: 
    user={{ user }} 
    key="{{ user_ssh_key }}"

- name: Make .ssh directory for hadoop user
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    mode: "0700"
    owner: "{{ user }}"
  delegate_to: "{{ item }}" 
  with_items: "{{ groups.workers }}" 

- name: Create master.pub file
  file:
    path: /home/{{ user }}/.ssh/master.pub
    state: touch
    mode: "0644"
    owner: "{{ user }}"
  delegate_to: "{{ item }}" 
  with_items: "{{ groups.workers }}" 


- name: Copy cluster public key from master to worker nodes using Method Pull
  tags: sync-pull
  synchronize:
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /home/{{ user }}/.ssh/master.pub
    mode: pull
  delegate_to: "{{ item }}" 
  with_items: "{{ groups.workers }}" 
  register: syncfile
  run_once: true