---
# tasks file for Distribute-Authentication-KeyPairs

- name: Make .ssh directory for hadoop user
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    mode: "0700"
    owner: "{{ user }}"
  delegate_to: "{{ item }}" 
  with_items: "{{ groups.workers }}"

- name: Create master.pub file
  file:
    path: /home/{{ user }}/.ssh/master.pub
    state: touch
    mode: "0644"
    owner: "{{ user }}"
  delegate_to: "{{ item }}" 
  with_items: "{{ groups.workers }}" 


- name: Copy cluster public key from master to worker nodes using Method Pull
  tags: sync-pull
  synchronize:
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /home/{{ user }}/.ssh/master.pub
    mode: pull
  delegate_to: "{{ item }}" 
  with_items: "{{ groups.workers }}" 
  register: syncfile
  run_once: true





 

